# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/decorrelation',
                'doc_host': 'https://kanglcn.github.io',
                'git_url': 'https://github.com/kanglcn/decorrelation',
                'lib_path': 'decorrelation'},
  'syms': {'decorrelation.shp': {'decorrelation.shp.ks_test': ('api/shp.html#ks_test', 'decorrelation/shp.py')}}}
