# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/decorrelation',
                'doc_host': 'https://kanglcn.github.io',
                'git_url': 'https://github.com/kanglcn/decorrelation',
                'lib_path': 'decorrelation'},
  'syms': { 'decorrelation.co': {'decorrelation.co.co_mat': ('API/co.html#co_mat', 'decorrelation/co.py')},
            'decorrelation.pl': {},
            'decorrelation.plot': {'decorrelation.plot.bg_alpha': ('API/plot.html#bg_alpha', 'decorrelation/plot.py')},
            'decorrelation.shp': {'decorrelation.shp.ks_test': ('API/shp.html#ks_test', 'decorrelation/shp.py')}}}
