# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/decorrelation',
                'doc_host': 'https://kanglcn.github.io',
                'git_url': 'https://github.com/kanglcn/decorrelation',
                'lib_path': 'decorrelation'},
  'syms': { 'decorrelation.co': { 'decorrelation.co.emperical_co': ('API/co.html#emperical_co', 'decorrelation/co.py'),
                                  'decorrelation.co.emperical_co_sp': ('API/co.html#emperical_co_sp', 'decorrelation/co.py'),
                                  'decorrelation.co.isPD': ('API/co.html#ispd', 'decorrelation/co.py'),
                                  'decorrelation.co.nearestPD': ('API/co.html#nearestpd', 'decorrelation/co.py'),
                                  'decorrelation.co.regularize_spectral': ('API/co.html#regularize_spectral', 'decorrelation/co.py')},
            'decorrelation.pl': { 'decorrelation.pl.emi': ('API/pl.html#emi', 'decorrelation/pl.py'),
                                  'decorrelation.pl.temp_coh': ('API/pl.html#temp_coh', 'decorrelation/pl.py')},
            'decorrelation.plot': {'decorrelation.plot.bg_alpha': ('API/plot.html#bg_alpha', 'decorrelation/plot.py')},
            'decorrelation.shp': {'decorrelation.shp.ks_test': ('API/shp.html#ks_test', 'decorrelation/shp.py')}}}