# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/API/utils.ipynb.

# %% auto 0
__all__ = ['ngjit', 'ngpjit']

# %% ../nbs/API/utils.ipynb 2
# Adapted from spatialpandas at https://github.com/holoviz/spatialpandas under BSD-2-Clause license.

# %% ../nbs/API/utils.ipynb 4
import numpy as np
from numba import jit

# %% ../nbs/API/utils.ipynb 5
ngjit = jit(nopython=True, nogil=True)
ngpjit = jit(nopython=True, nogil=True, parallel=True)
