# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/moraine',
                'doc_host': 'https://kanglcn.github.io',
                'git_url': 'https://github.com/kanglcn/moraine',
                'lib_path': 'moraine'},
  'syms': {'moraine.core': {'moraine.core.foo': ('core.html#foo', 'moraine/core.py')}}}
